baseURL = "https://miguel.moll.ninja"
title = "betcha can't stick it"
languageCode = "en-us"
theme = "devise"
relativeURLs = true
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = true
copyright = "&copy; Copyright Miguel Moll"

# Main menu items
[menu]
  [[menu.main]]
    identifier = "Home"
    name = "Home"
    title = "Home"
    url = "/"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = -100

[params]
  description = "Your meta description"      # Your meta description of the site
  header_title = "Miguel Moll"               # Your header title
  header_subtitle = "Random thoughts/findings I'd like to remember and share. Most likely gamedev and software related." 
  home_image = "/images/profile-pic.jpeg"          # Path to header image starting from the static directory
  recent_posts = 5                           # Max amount of recent posts to show
  mainSections = ["posts", "post", "blog"]   # Main sections to include in recent posts
  #[params.style]                             # CSS style overrides
  #  backgroundColor = "#f8f9fa"
  #  fontColor = "#212529"
  [[params.social]]
    fa_icon = "fab fa-youtube fa-1x"
    href = "https://www.youtube.com/@MiguelMoll"
  [[params.social]]
    fa_icon = "fab fa-twitter fa-1x"
    href = "https://twitter.com/radioact1ve"
  [[params.social]]
    fa_icon = "fab fa-mastodon fa-1x"
    href = "https://mastodon.gamedev.place/@radioact1ve"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"
    href = "https://github.com/MiguelMoll"
